from __future__ import annotations
from typing import Protocol, Any
from decimal import Decimal
from .core import MarketTick, Order, Fill, OrderIntent

class DataProvider(Protocol):
    def ticks(self, dataset_id:str)->list[MarketTick]: ...
class Broker(Protocol):
    def submit(self,intent:OrderIntent)->Order: ...
class FeePlugin(Protocol):
    def fee(self,price:Decimal,quantity:Decimal,liquidity:str)->Decimal: ...
class SlippagePlugin(Protocol):
    def apply(self,price:Decimal,side:str)->Decimal: ...
class LatencyPlugin(Protocol):
    def total_ms(self)->int: ...
class ExecutionPlugin(Protocol):
    def execute(self,order:Order,tick:MarketTick)->list[Fill]: ...
class FitnessPlugin(Protocol):
    def evaluate(self,metrics:dict[str,float])->dict[str,float]: ...
class MutationPlugin(Protocol):
    def mutate(self,genome:Any)->Any: ...
class CrossoverPlugin(Protocol):
    def crossover(self,left:Any,right:Any)->Any: ...
class PortfolioAllocator(Protocol):
    def allocate(self,strategies:list[dict])->dict[str,Decimal]: ...
class ExchangeAdapter(Protocol):
    def market(self)->Any: ...

class PluginRegistry:
    def __init__(self): self._plugins={}
    def register(self,name:str,plugin:Any): self._plugins[name]=plugin
    def get(self,name:str): return self._plugins[name]
    def names(self): return tuple(sorted(self._plugins))
